language: node_js

matrix:
  include:
    - node_js: "10.6"
      env:
        - DISABLE_TESTS=false
        - LINTING=true

sudo: false

install:
  - travis_retry npm install

script:
  - npm run test
