service: sns-sqs-service

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-southeast-2
  stage: ${opt:stage, 'dev'}

custom:
  topicArn: !Ref Topic

functions:
  processEvent:
    handler: handler.handler
    events:
      - snsSqs:
          name: ResourcePrefix
          topicArn: ${self:custom.topicArn}
          batchSize: 2
          maxRetryCount: 2
          filterPolicy:
            pet:
              - dog
              - cat

resources:
  Resources:
    Topic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: TestTopic

plugins:
  - '@agiledigital/serverless-sns-sqs-lambda'
