# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    # Don't build if Semantic Release pushes a ci skip commit
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      # Not the same as GITHUB_TOKEN
      # This token authenticates on behalf of the maintainer, not github actions itself
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # Skip post-install scripts here, as a malicious
      # script could steal NODE_AUTH_TOKEN.
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn run build
      - name: Type Coverage
        run: yarn run type-coverage
      - name: Test
        run: yarn run test
      - name: Run Semantic Release
        run: yarn semantic-release
        if: matrix.node-version == '12.x'
